name: apunco
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  mime: ^1.0.4
  file_picker: ^10.0.0
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  provider: ^6.1.5
  flutter_keyboard_visibility: ^6.0.0
  open_filex: ^4.7.0 
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
